# Generated by Django 3.1.6 on 2021-02-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linktree', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='link',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
