# Generated by Django 3.1.7 on 2021-02-28 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linktree', '0002_auto_20210225_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='linktree.user'),
        ),
    ]
